#!/bin/bash
################################################################################
# Script for Installation: OpenNebula V4.12 on Ubuntu 14.04.2 LTS Server
# Author: Lahmizzar Valeryon, devXive 2015
#
#-------------------------------------------------------------------------------
#
# Quickstart:
# OpenNebula on Ubuntu 14.04 as the operating system and KVM as the hypervisor
#
# This script will prepare a clean Ubuntu to work as a host for OpenNebula
#
#
# The "Nodes" will be used to execute virtual machines. However it is recommended
# execute virtual machines in hosts with virtualization extensions. To test if
# your host supports virtualization extensions, please run:
#
# grep -E 'svm|vmx' /proc/cpuinfo
#
# If you don't get any output you probably don't have virtualization extensions
# supported/enabled in your server.
#-------------------------------------------------------------------------------
# USAGE:
#
# one-node-install
#
# EXAMPLE:
# ./one-node-install.sh
#
################################################################################

#--------------------------------------------------
#Fixed parameters for OpenNebula Working Node
#--------------------------------------------------
ONE_FRONTEND_SERVER_IP="10.10.1.1"
ONE_ADMIN="oneadmin"

## General Network Settings
NT_ADDRESS="10.10.1.2"
NT_NETMASK="255.255.240.0"
NT_NETWORK="10.10.0.0"
NT_BROADCAST="10.10.15.255"
NT_GATEWAY="10.10.0.1"
NT_DNS_ADDRESS="10.10.0.1"


#--------------------------------------------------
# Install latest updates
#--------------------------------------------------
echo -e "\n---- Install latest updates ----"
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get autoremove


#--------------------------------------------------
# Install the repo
#--------------------------------------------------
echo -e "\n---- Install the repo ----"
# sudo wget -q -O- http://downloads.opennebula.org/repo/Ubuntu/repo.key | apt-key add -
sudo su root -c "wget -q -O- http://downloads.opennebula.org/repo/Ubuntu/repo.key | apt-key add -"
sudo su root -c "echo 'deb http://downloads.opennebula.org/repo/4.12/Ubuntu/14.04/ stable opennebula' > /etc/apt/sources.list.d/opennebula.list"
sudo apt-get update
sudo apt-get upgrade -y


#--------------------------------------------------
# Install the required packages
#--------------------------------------------------
echo -e "\n---- Install the required packages ----"
sudo apt-get install opennebula-node nfs-common bridge-utils -y


#--------------------------------------------------
# Configure the Network
#--------------------------------------------------
echo -e "\n---- Configure the Network ----"
sudo cp /etc/network/interfaces /etc/network/interfaces_bkp

sudo su root -c "cat << EOT > /etc/network/interfaces
# This file was auto-generated by the OpenNebula install script for nodes
# The original 'interfaces' file has been renamed to 'interfaces_bkp'

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto br0
iface br0 inet static
	address $NT_ADDRESS
	netmask $NT_NETMASK
	network $NT_NETWORK
	broadcast $NT_BROADCAST
	gateway $NT_GATEWAY
	dns-addresses $NT_DNS_ADDRESS
	bridge_ports eth0
	bridge_fd 9
	bridge_hello 2
	bridge_maxage 12
	bridge_stp off
EOT"

sudo /etc/init.d/networking restart


#--------------------------------------------------
# Configure NFS
#--------------------------------------------------
echo -e "\n---- Configure NFS ----"
sudo cp /etc/fstab /etc/fstab.bkp
NFS_VAR="$ONE_FRONTEND_SERVER_IP:/var/lib/one/	/var/lib/one/	nfs	soft,intr,rsize=8192,wsize=8192,noauto"

sudo su root -c "echo $'\n\n'$NFS_VAR$'\n' >> /etc/fstab"

sudo mount /var/lib/one/


#--------------------------------------------------
# Configure Qemu
#--------------------------------------------------
echo -e "\n---- Configure Qemu ----"
sudo su root -c "cat << EOT > /etc/libvirt/qemu.conf
user  = "$ONE_ADMIN"
group = "$ONE_ADMIN"
dynamic_ownership = 0
EOT"

sudo service libvirt-bin restart


echo "Done! The OpenNebula node is ready now. Add the host '$HOSTNAME' via Sunstone or CLI on ONE-Server (IP: $ONE_FRONTEND_SERVER_IP) now"